### ISSUE TITLE
-time seems to be ignored

### ISSUE THREAD

**Issue by Arzte** [wavexx/acpilight#1] opened 2016-04-19 01:11 UTC
No matter what time I put in there it just changes instantly.

**Comment by wavexx** [comment] 2016-04-19 08:39
On Tue, Apr 19 2016, Benjamin Hoffmeyer notifications@github.com wrote:

> No matter what time I put in there it just changes instantly.

Indeed, -time and -steps are not implemented currently.

**Comment by Arzte** [comment] 2016-04-20 15:08
That's inconvenient, I'm using this for redshift. Thanks for letting me know.

**Comment by wavexx** [comment] 2016-04-21 10:09
On Wed, Apr 20 2016, Benjamin Hoffmeyer notifications@github.com wrote:

> That's inconvenient, I'm using this for redshift. Thanks for letting me know.

How does redshift calls time/step?

**Comment by Arzte** [comment] 2016-04-21 15:32
Through a bash script hook, 

```
#!/bin/sh

# Set brightness via xbrightness when redshift status changes

# Set brightness values for each status.
# Range from 1 to 100 is valid
brightness_day="100"
brightness_transition="50"
brightness_night="10"
# Set fade time for changes to one minute
fade_time=60000
ctrl=acpi_video0

case $1 in
    period-changed)
        case $3 in
            night)
                /home/name/xbacklight -set $brightness_night -time $fade_time -ctrl $ctrl
                ;;
            transition)
                /home/name/xbacklight -set $brightness_transition -time $fade_time -ctrl $ctrl
                ;;
            day)
                /home/name/xbacklight -set $brightness_day -time $fade_time -ctrl $ctrl
                ;;
        esac
        ;;
esac
```

**Comment by wavexx** [comment] 2016-04-22 15:17
Fair enough, I never had a reason to implement time/steps (I always wanted instantaneous changes).
I implemented it now, could you check if it works as intended?

The default for steps though is 0, which disables the transition by default. If nobody complains, I'd prefer the current behavior.

**Comment by Arzte** [comment] 2016-04-23 01:49
They work perfectly, much better with these implanted, thanks so much!

**Comment by wavexx** [comment] 2016-04-23 11:57
Great! Closing then.

**Closed as completed by wavexx** 2016-04-23 11:57 UTC
